version: '3'

# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxied containers. 
# networks:
#   default:
#     external:
#       name: nginx-proxy

volumes:
  conf:
  vhost:
  html:
  certs:

services:

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
      - html:/var/www/acme
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion:stable
  #   restart: always
  #   container_name: nginx-proxy-le
  #   depends_on:
  #     - nginx
  #   environment:
  #     NGINX_PROXY_CONTAINER: nginx-proxy
  #   volumes:
  #     - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
  #     - ${PWD}/nginx/certs:/etc/nginx/certs:rw
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html

  traefik:
    image: traefik:alpine
    container_name: traefik-proxy
    restart: always
    hostname: traefik
#    environment:
#      - INFLUXDB_ADDRESS=traefik-write:bYXbKA2QCnXRGEfmpJzk=ijJ?mxFbQmP4cadRtbpsMAWzGscerZBeAg@influxdb:8089
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/traefik/rules:/rules
      - ${PWD}/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro