version: '3'

# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxied containers. 
# networks:
#   default:
#     external:
#       name: nginx-proxy

volumes:
  conf:
  vhost:
  html:
  certs:

services:

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
  #     - certs:/etc/nginx/certs:ro
  #     - html:/var/www/acme
  #   labels:
  #     - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
  #     - traefik.enable=true
  #     - traefik.backend=nginx
  #     - traefik.frontend.rule=Host:ve.josverheij.nl
  #     - traefik.port=443

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion:stable
  #   restart: always
  #   container_name: nginx-proxy-le
  #   depends_on:
  #     - nginx
  #   environment:
  #     NGINX_PROXY_CONTAINER: nginx-proxy
  #   volumes:
  #     - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
  #     - ${PWD}/nginx/certs:/etc/nginx/certs:rw
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html

  traefik:
    image: traefik:alpine
    container_name: traefik-proxy
    restart: always
    hostname: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ${PWD}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/traefik/rules:/rules
      - ${PWD}/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro

  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - 1194:1194/udp
    restart: always
    volumes:
      - {PWD}/openvpn/data/conf:/etc/openvpn