# doppio.hippoline.nl.toml
[backends]
  [backends.doppio]
    [backends.doppio.servers]
      [backends.doppio.servers.server0]
        url = "http://10.70.0.8:80"

[frontends]
  [frontends.doppio]
    backend = "doppio"
    passHostHeader = true

    [frontends.doppio.routes]
      [frontends.doppio.routes.route0]
        rule = "Host:doppio.hippoline.nl"

    [frontends.doppio.redirect]
      regex = "^https://doppio.hippoline.nl/$"
      replacement = "https://doppio.hippoline.nl/qlikview"