# KlantjeSjoerd.hippoline.nl.toml
[backends]
  [backends.KlantjeSjoerd]
    [backends.KlantjeSjoerd.servers]
      [backends.KlantjeSjoerd.servers.server0]
        url = "http://10.70.1260.7:80"

[frontends]
  [frontends.jgz]
    backend = "KlantjeSjoerd"
    passHostHeader = true

    [frontends.KlantjeSjoerd.routes]
      [frontends.KlantjeSjoerd.routes.route0]
        rule = "Host:KlantjeSjoerd.hippoline.nl"

    [frontends.KlantjeSjoerd.redirect]
      regex = "^https://KlantjeSjoerd.hippoline.nl/$"
      replacement = "https://KlantjeSjoerd.hippoline.nl/qlikview"
      