# validexpress.hippoline.nl.toml
[backends]
  [backends.test]
    [backends.test.servers]
      [backends.test.servers.server0]
        url = "https://10.70.0.100:443"

[frontends]
  [frontends.test]
    backend = "test"
    passHostHeader = true

    [frontends.test.routes]
      [frontends.test.routes.route0]
        rule = "Host:test.hippoline.nl"
      