# tpscan.hippoline.nl.toml
[backends]
  [backends.testgysbert]
    [backends.testgysbert.servers]
      [backends.testgysbert.servers.server0]
        url = "http://10.70.0.7:80"

[frontends]
  [frontends.testgysbert]
    backend = "testgysbert"
    passHostHeader = true

    [frontends.testgysbert.routes]
      [frontends.testgysbert.routes.route0]
        rule = "Host:testgysbert.hippoline.nl"

    [frontends.testgysbert.redirect]
      regex = "^https://testgysbert.hippoline.nl/$"
      replacement = "https://testgysbert.hippoline.nl/qlikview"
      