# validexpress.hippoline.nl.toml
[backends]
  [backends.validexpressSjoerd]
    [backends.validexpressSjoerd.servers]
      [backends.validexpressSjoerd.servers.server0]
        url = "https://10.70.0.105:443"

[frontends]
  [frontends.validexpressSjoerd]
    backend = "validexpressSjoerd"
    passHostHeader = true

    [frontends.validexpressSjoerd.routes]
      [frontends.validexpressSjoerd.routes.route0]
        rule = "Host:validexpressSjoerd.hippoline.nl"
      