# validexpress.hippoline.nl.toml
[backends]
  [backends.validexpress]
    [backends.validexpress.servers]
      [backends.validexpress.servers.server0]
        url = "https://10.70.0.5:443"

[frontends]
  [frontends.validexpress]
    backend = "validexpress"
    passHostHeader = true
    InsecureSkipVerify = true

    [frontends.validexpress.routes]
      [frontends.validexpress.routes.route0]
        rule = "Host:validexpress.josverheij.nl"

    [frontends.validexpress.redirect]
      